### ISSUE TITLE
Still looking to improve this?

### ISSUE THREAD

**Issue by jquincy-manticore** [An00b1sR0cks/FFPRSaveEditor#1]
I might have time to do the work to deserialize the json into a class structure. I haven't worked much into WPF so I'm not sure if I could tackle that.

**Comment by Anub1sR0cks** [comment]
Sure, by all means. I might regain interest in writing the UI frontend.

**Comment by JackQuincy** [comment]
Using Personal account this time.  Last time I was on my phone and didn't realize it was signed into my work account.
I made a PR for doing an initial pass on stuff for FF1.  Looks like someone else did a less manual solution already.  Only thing my stuff has that theirs doesn't is I figured out what some of the enum ints meant by inspecting my save file.
