### ISSUE TITLE
Problem you mentioned executable

### ISSUE THREAD

**Issue by minecraft619** [An00b1sR0cks/FFPRSaveEditor#4]
Where is the exe file? All i am seeing is a .cs and a .csproj file. I have zero knowledge on how to do this.

**Comment by Anub1sR0cks** [comment]
This is a source code repository.

The Windows executables can be downloaded from this zip file:
https://github.com/Anub1sR0cks/FFPRSaveEditor/releases/tag/v0.1.0-proto
