### ISSUE TITLE
Switch PR Saves

### ISSUE THREAD

**Issue by bad1dea** [An00b1sR0cks/FFPRSaveEditor#6]
Hey,

Just curious, tool works great to decrypt PC (What it is intended to do).

I've noticed it does not do the Switch Saves currently, are you interested in doing so? It may be as simple as flipping the byte order/endian.

File names are basically the same, encrypted.. similar to what I have for the PC..

```
SWITCH SAVE
C:\Temp\FFPR SGE>FFPRSaveEditor.Decrypt.exe 7nCxyzTwG31W3Zlg70mo751W8ETH1n+Km0dWOzRU84Y= test.json
The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
```

```
PC SAVE
C:\Temp\FFPR SGE>FFPRSaveEditor.Decrypt.exe 7nCxyzTwG31W3Zlg70mo751W8ETH1n+Km0dWOzRU84Y= test.json
Successfully decrypted 751332 byte(s).
Remember to backup your save game files!
```

I can send you multiple save files if you wish to look into it further.

**Comment by Anub1sR0cks** [comment]
Sure, send me one and I'll see what I can do. I believe Switch saves may have an extra level of encryption. I don't have a modded Switch myself so it would have to be all guesswork.

**Comment by lukahn** [comment]
I'd be interested in this too, and can provide save files for testing. Here's the start of a new game for FF1 on the Switch (v1.01):
[01000EA014150000.zip](https://github.com/Anub1sR0cks/FFPRSaveEditor/files/11855551/01000EA014150000.zip)

And some screenshots showing the contents:
![01000ea014150000_2023-06-24_16-02-24-806](https://github.com/Anub1sR0cks/FFPRSaveEditor/assets/5970051/9fecbc8c-380c-46b6-a841-5ab314d4c6dc)

![01000ea014150000_2023-06-24_16-05-04-049](https://github.com/Anub1sR0cks/FFPRSaveEditor/assets/5970051/53d10378-abfa-45b5-a0b0-1d2aed99ef29)

**Comment by Anub1sR0cks** [comment]
I've analyzed a few of the Switch save files. Unfortunately it appears that Square-Enix has changed the saving/loading hashword in the console version of the game -- probably because I reverse engineered the initial PC cipher. Without access to a Switch debugging kit it's unlikely I can take a crack at it like I can with the PC version of games, sorry :(

**Comment by lukahn** [comment]
Thanks for looking into it anyway, I appreciate your time. I might take a quick look at the memory to see if I can find the password/salt values, but otherwise I'll just switch to the Steam version instead.
